### ISSUE TITLE
Dependency requirements cannot be resolved

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/multi-echo-data-analysis#32]
PySPFM's Nilearn version is too restrictive. It looks like https://github.com/Paradigm-Free-Mapping/pySPFM/pull/105 is failing. @eurunuela will you be able to resolve that?

**Comment by eurunuela** [comment]
If I remember correctly, the issue is related to changes in the GLM functions. I will have to have a look to see what has changed.

**Comment by eurunuela** [comment]
Okay, I just merged the version bump in https://github.com/Paradigm-Free-Mapping/pySPFM/pull/105
